# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 07:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=50, verbose_name='Место нахождения')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(blank=True, help_text='Вводить номер в федеральном формате, без кода страны 8 или +7', max_length=10, verbose_name='Номер телефона')),
                ('gender', models.CharField(blank=True, choices=[('man', 'Мужской'), ('woman', 'Женский')], max_length=50, verbose_name='Пол')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
