# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-25 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0025_auto_20190625_1739'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='factory',
            field=models.ManyToManyField(help_text='Выбрать сервисные компании доступные пользователю', related_name='factory_select', to='reference_books.Factory', verbose_name='Производства (доступные)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='factory_current',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory_current', to='reference_books.Factory', verbose_name='Производство (текущая)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='factory_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory_default', to='reference_books.Factory', verbose_name='Производство (по умолчанию)'),
        ),
    ]
