# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-23 06:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reference_books', '0028_status_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('Descript', models.TextField(blank=True, verbose_name='Примечание')),
                ('Date_start', models.DateField(verbose_name='Дата начала')),
                ('Date_end', models.DateField(blank=True, null=True, verbose_name='Дата окнчания')),
                ('DateTime_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('DateTime_update', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('Coworker', models.ForeignKey(help_text='Для указания нескольких исполнителей используйте клавишу Ctrl', on_delete=django.db.models.deletion.CASCADE, to='reference_books.coworker', verbose_name='Исполнители')),
                ('Create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_creator', to=settings.AUTH_USER_MODEL)),
                ('Factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.Factory', verbose_name='Организация')),
                ('Update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_modifying', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reference_books.status_project', verbose_name='Статус выполнения')),
            ],
            options={
                'verbose_name': 'Проект ',
                'verbose_name_plural': 'Общие проекты',
                'permissions': (('projects_list_view', 'Проекты. Просмотр списка'), ('projects_item_view', 'Проекты. Просмотр записи'), ('projects_item_add', 'Проекты. Добавление записи'), ('projects_item_edit', 'Проекты. Редактирование записи')),
            },
        ),
    ]
