# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-22 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept_okk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='okk_control_grain_moisture',
            options={'permissions': (('list_view', 'КУЗМ. Просмотр списка'), ('item_view', 'КУЗМ. Просмотр записи'), ('item_add', 'КУЗМ. Добавление записи'), ('item_edit', 'КУЗМ. Редактирование записи')), 'verbose_name': 'Замер ', 'verbose_name_plural': 'Контроль увлажнения зерна на мельнице (КУЗМ)'},
        ),
        migrations.AlterModelOptions(
            name='okk_operational_quality_control_flour',
            options={'permissions': (('list_view', 'ОККММ. Просмотр списка'), ('item_view', 'ОККММ. Просмотр записи'), ('item_add', 'ОККММ. Добавление записи'), ('item_edit', 'ОККММ. Редактирование записи')), 'verbose_name': 'Партия ', 'verbose_name_plural': 'Оперативный качественный контроль муки на мельнице (ОККММ)'},
        ),
        migrations.AlterModelOptions(
            name='okk_operational_quality_control_semolina',
            options={'permissions': (('list_view', 'ОККМнМ. Просмотр списка'), ('item_view', 'ОККМнМ. Просмотр записи'), ('item_add', 'ОККМнМ. Добавление записи'), ('item_edit', 'ОККМнМ. Редактирование записи')), 'verbose_name': 'Замер ', 'verbose_name_plural': 'Оперативный контроль качества манной муки (ОККМнМ)'},
        ),
        migrations.AlterModelOptions(
            name='okk_packproducts_quality_control',
            options={'permissions': (('list_view', 'ККФП. Просмотр списка'), ('item_view', 'ККФП. Просмотр записи'), ('item_add', 'ККФП. Добавление записи'), ('item_edit', 'ККФП. Редактирование записи')), 'verbose_name': 'Партия ', 'verbose_name_plural': 'Контроль качества фасованной продукции (ККФП)'},
        ),
        migrations.AlterModelOptions(
            name='okk_wheat_quality_control',
            options={'permissions': (('list_view', 'ВККП. Просмотр списка'), ('item_view', 'ВККП. Просмотр записи'), ('item_add', 'ВККП. Добавление записи'), ('item_edit', 'ВККП. Редактирование записи')), 'verbose_name': 'Партия ', 'verbose_name_plural': 'Входной контроль качества пшеницы (ВККП)'},
        ),
    ]
