# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-11 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_okk', '0004_auto_20190411_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okk_control_grain_moisture',
            name='Moisture_excuse1',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Отлёжка 1'),
        ),
        migrations.AlterField(
            model_name='okk_control_grain_moisture',
            name='Moisture_excuse2',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Отлёжка 2'),
        ),
        migrations.AlterField(
            model_name='okk_control_grain_moisture',
            name='Moisture_excuse3',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Отлёжка 3'),
        ),
    ]
