# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-11 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept_okk', '0005_auto_20190411_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='okk_control_grain_moisture',
            name='note',
        ),
    ]
