# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-05 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_okk', '0006_remove_okk_control_grain_moisture_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okk_wheat_quality_control',
            name='GrainImpurity_Barley',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ячмень, %'),
        ),
        migrations.AlterField(
            model_name='okk_wheat_quality_control',
            name='GrainImpurity_Beaten',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Битое/Щуплое, %'),
        ),
        migrations.AlterField(
            model_name='okk_wheat_quality_control',
            name='GrainImpurity_Eaten',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Изъеденное/Зеленое, %'),
        ),
        migrations.AlterField(
            model_name='okk_wheat_quality_control',
            name='GrainImpurity_Rye',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Рожь/Поврежденное, %'),
        ),
        migrations.AlterField(
            model_name='okk_wheat_quality_control',
            name='GrainImpurity_Sprouted',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Проросшее, %'),
        ),
        migrations.AlterField(
            model_name='okk_wheat_quality_control',
            name='LotWeight',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Масса партии'),
        ),
    ]
