# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-27 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0027_auto_20190626_1703'),
        ('dept_okk', '0008_auto_20190619_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='okk_control_grain_moisture',
            name='Factory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reference_books.Factory', verbose_name='Организация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='okk_operational_quality_control_flour',
            name='Factory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reference_books.Factory', verbose_name='Организация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='okk_operational_quality_control_semolina',
            name='Factory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reference_books.Factory', verbose_name='Организация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='okk_packproducts_quality_control',
            name='Factory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reference_books.Factory', verbose_name='Организация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='okk_wheat_quality_control',
            name='Factory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reference_books.Factory', verbose_name='Организация'),
            preserve_default=False,
        ),
    ]
