# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_task',
            name='done',
        ),
        migrations.RemoveField(
            model_name='user_task',
            name='done_description',
        ),
        migrations.RemoveField(
            model_name='user_task',
            name='limitation',
        ),
        migrations.RemoveField(
            model_name='user_task',
            name='responsible',
        ),
        migrations.AddField(
            model_name='user_task',
            name='Date_limit',
            field=models.DateField(default='2018-01-01', verbose_name='Дата исполнения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_task',
            name='Time_limit',
            field=models.TimeField(default='00:00', verbose_name='Время исполнения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_task',
            name='Update_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='update_user', to=settings.AUTH_USER_MODEL, verbose_name='Обновил'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_task',
            name='executor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='executor', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_task',
            name='status',
            field=models.CharField(choices=[('open', 'Открыта'), ('work', 'Выполняется'), ('transfer', 'Перенесено'), ('cancelled', 'Исполнено'), ('complete', 'Исполнено')], default='open', max_length=100, verbose_name='Статус выполнения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_task',
            name='work_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание выполнения'),
        ),
        migrations.AlterField(
            model_name='user_task',
            name='Create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_user', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='user_task',
            name='description',
            field=models.TextField(verbose_name='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='user_task',
            name='notification',
            field=models.CharField(choices=[('system', 'системное'), ('sms', 'СМС'), ('email', 'на эл.почту'), ('nonotification', 'системное')], max_length=100, verbose_name='Способ уведомления о статусе заявки'),
        ),
        migrations.DeleteModel(
            name='type_notification',
        ),
    ]
