# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-16 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_user_task_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_task',
            name='Update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_user', to=settings.AUTH_USER_MODEL, verbose_name='Обновил'),
        ),
        migrations.AlterField(
            model_name='user_task',
            name='notification',
            field=models.CharField(choices=[('system', 'системное'), ('sms', 'СМС'), ('email', 'на эл.почту'), ('nonotification', 'не уведомлять')], default='system', max_length=100, verbose_name='Способ уведомления о статусе заявки'),
        ),
        migrations.AlterField(
            model_name='user_task',
            name='status',
            field=models.CharField(choices=[('open', 'Открыта'), ('work', 'Выполняется'), ('transfer', 'Перенесено'), ('cancelled', 'Отменено'), ('complete', 'Исполнено')], default='open', max_length=100, verbose_name='Статус выполнения'),
        ),
    ]
