# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-16 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20181216_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_task',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Прочтено'),
        ),
        migrations.AlterField(
            model_name='user_task',
            name='high_importance',
            field=models.BooleanField(default=False, verbose_name='Высокая важность'),
        ),
    ]
