# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-30 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20181216_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_task',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.typenotification_task', verbose_name='Способ уведомления о статусе заявки'),
        ),
        migrations.AlterField(
            model_name='user_task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.status_task', verbose_name='Статус выполнения'),
        ),
    ]
