# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-30 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20190130_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_task',
            options={'permissions': (('task_list_view', 'КУЗМ. Просмотр списка'), ('task_item_view', 'КУЗМ. Просмотр записи'), ('task_item_add', 'КУЗМ. Добавление записи'), ('task_item_edit', 'КУЗМ. Редактирование записи')), 'verbose_name': 'Задача ', 'verbose_name_plural': 'Список задач '},
        ),
    ]
