# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('tasks', '0008_auto_20190130_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_task',
            name='executor',
        ),
        migrations.AddField(
            model_name='user_task',
            name='executors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='auth.Group', verbose_name='Группа исполнителей'),
            preserve_default=False,
        ),
    ]
