# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coworker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='ФИО сотрудника')),
                ('working', models.BooleanField(default=True, help_text='Если сотрудник уволен, снимите галочку', verbose_name='Действующий сотрудник')),
            ],
            options={
                'verbose_name': 'Исполнитель/Сотрудник ',
                'verbose_name_plural': 'Список исполнителей ',
            },
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Должность')),
                ('slug', models.SlugField(verbose_name='алиас')),
            ],
            options={
                'verbose_name': 'Должность ',
                'verbose_name_plural': 'Список должностей ',
            },
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Состояние')),
                ('slug', models.SlugField(unique=True, verbose_name='Ключ статуса')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет строки')),
            ],
            options={
                'verbose_name': 'Статус заявки ',
                'verbose_name_plural': 'Статусы заявок ',
            },
        ),
        migrations.AddField(
            model_name='coworker',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.posts', verbose_name='Должность'),
        ),
    ]
