# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('businessman', 'Индивидуальный предприниматель'), ('company', 'Организация')], max_length=50, verbose_name='Тип поставщика')),
                ('shortname', models.CharField(max_length=150, verbose_name='Краткое наименование')),
                ('fullname', models.CharField(max_length=300, verbose_name='Полное наименование')),
                ('inn', models.CharField(max_length=15, verbose_name='ИНН')),
            ],
        ),
    ]
