# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0003_auto_20181009_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Культура ',
                'verbose_name_plural': 'Зерновые культуры ',
            },
        ),
        migrations.AlterField(
            model_name='cereal_crop',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
    ]
