# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0004_auto_20181010_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Ключ категории')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('mptt_level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='reference_books.area', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Участок/Отдел ',
                'verbose_name_plural': 'Структура подразделений ',
            },
        ),
        migrations.CreateModel(
            name='fixed_assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование')),
                ('norm', models.IntegerField(verbose_name='Учтено, шт.')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.area', verbose_name='Подразделение (место установки)')),
            ],
            options={
                'verbose_name': 'Установка ',
                'verbose_name_plural': 'Основные средства ',
            },
        ),
        migrations.CreateModel(
            name='magnetic_installations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Установка ',
                'verbose_name_plural': 'Магнитные установки ',
            },
        ),
        migrations.AlterModelOptions(
            name='pasta',
            options={'verbose_name': 'Вид ', 'verbose_name_plural': 'Макаронные изделия '},
        ),
        migrations.AddField(
            model_name='coworker',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reference_books.area', verbose_name='Подразделение'),
            preserve_default=False,
        ),
    ]
