# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0005_auto_20181105_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='inn',
            field=models.CharField(blank=True, max_length=15, verbose_name='ИНН'),
        ),
    ]
