# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-22 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0009_auto_20190122_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cereal_crop',
            options={'verbose_name': 'Культура ', 'verbose_name_plural': 'Зерновые культуры '},
        ),
        migrations.AlterModelOptions(
            name='coworker',
            options={'verbose_name': 'Исполнитель/Сотрудник ', 'verbose_name_plural': 'Список исполнителей '},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Контрагент ', 'verbose_name_plural': 'Контрагенты '},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Вид ', 'verbose_name_plural': 'Продукция '},
        ),
    ]
