# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-01 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0012_bhm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhm',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
    ]
