# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-14 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0013_auto_20190201_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True, verbose_name='Ключ статуса')),
            ],
            options={
                'verbose_name': 'Силос ',
                'verbose_name_plural': 'Установки силосные ',
            },
        ),
    ]
