# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0014_sil'),
    ]

    operations = [
        migrations.CreateModel(
            name='constants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('slug', models.SlugField(verbose_name='алиас')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Константа ',
                'verbose_name_plural': 'Список констант ',
            },
        ),
        migrations.AlterModelOptions(
            name='bhm',
            options={'ordering': ['name'], 'verbose_name': 'БХМ ', 'verbose_name_plural': 'Установки БХМ '},
        ),
        migrations.AlterModelOptions(
            name='sil',
            options={'ordering': ['name'], 'verbose_name': 'Силос ', 'verbose_name_plural': 'Установки силосные '},
        ),
    ]
