# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0016_tare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month_num', models.IntegerField(verbose_name='Номер месяца')),
                ('Month_name', models.CharField(max_length=50, verbose_name='Название месяца')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
