# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0017_month_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='status_machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Состояние ',
                'verbose_name_plural': 'Состояния станков ',
            },
        ),
        migrations.DeleteModel(
            name='Month_list',
        ),
    ]
