# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0019_status_machine_class_b4_td'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine_production',
            options={'ordering': ['id'], 'verbose_name': 'Станок ', 'verbose_name_plural': 'Станки для производства макарон '},
        ),
        migrations.RemoveField(
            model_name='posts',
            name='slug',
        ),
    ]
