# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-17 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0020_auto_20190424_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='types_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30, verbose_name='Абревиатура')),
                ('slug', models.SlugField(unique=True, verbose_name='Алиас')),
                ('full_name', models.TextField(verbose_name='Подробное описание')),
            ],
            options={
                'verbose_name_plural': 'Типы контрагентов ',
                'verbose_name': 'Тип контрагентов ',
            },
        ),
        migrations.AlterModelOptions(
            name='coworker',
            options={'ordering': ['fullname'], 'verbose_name': 'Исполнитель/Сотрудник ', 'verbose_name_plural': 'Список исполнителей '},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['shortname'], 'verbose_name': 'Контрагент ', 'verbose_name_plural': 'Контрагенты '},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['id'], 'verbose_name': 'Должность ', 'verbose_name_plural': 'Список должностей '},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['id'], 'verbose_name': 'Вид ', 'verbose_name_plural': 'Продукция '},
        ),
        migrations.RemoveField(
            model_name='partner',
            name='type',
        ),
    ]
