# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-17 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0021_auto_20190517_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reference_books.types_client', verbose_name='Тип поставщика'),
            preserve_default=False,
        ),
    ]
