# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-25 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0023_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True, verbose_name='алиас')),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.City', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Сервисная компания ',
                'verbose_name_plural': 'Список сервисных компаний ',
            },
        ),
    ]
