# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-25 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0024_servicecompanies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceCompanies',
            new_name='Factory',
        ),
        migrations.AlterModelOptions(
            name='factory',
            options={'verbose_name': 'Фабрика/завод ', 'verbose_name_plural': 'Список производств '},
        ),
    ]
