# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-26 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0026_factory_descript'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['Name'], 'verbose_name': 'Город ', 'verbose_name_plural': 'Список городов '},
        ),
        migrations.RemoveField(
            model_name='factory',
            name='slug',
        ),
    ]
