# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 18:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference_books', '0006_auto_20181105_1247'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product_equipment_breakdown_repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(verbose_name='Дата и время контроля')),
                ('Gang', models.CharField(choices=[('line_gang1', 'Смена 1'), ('line_gang2', 'Смена 2')], max_length=30, verbose_name='Смена')),
                ('Event', models.TextField(verbose_name='Описание события')),
                ('Action', models.TextField(verbose_name='Описание события')),
                ('DateTime_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('DateTime_update', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('Coworker', models.ManyToManyField(help_text='Для указания нескольких исполнителей используйте клавишу Ctrl', to='reference_books.coworker', verbose_name='Исполнители')),
                ('Create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_ebr_creator', to=settings.AUTH_USER_MODEL)),
                ('Update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_ebr_modifying', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись событий ',
                'verbose_name_plural': 'Учет поломок и ремонта оборудования',
            },
        ),
        migrations.CreateModel(
            name='product_line_operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(verbose_name='Дата и время контроля')),
                ('Line', models.CharField(choices=[('line_byuler1', 'Линия 1'), ('line_byuler2', 'Линия 2')], max_length=30, verbose_name='Линия')),
                ('Gang', models.CharField(choices=[('line_gang1', 'Смена 1'), ('line_gang2', 'Смена 2')], max_length=30, verbose_name='Смена')),
                ('Event', models.TextField(verbose_name='Описание события')),
                ('Action', models.TextField(verbose_name='Описание события')),
                ('DateTime_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('DateTime_update', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('Coworker', models.ManyToManyField(help_text='Для указания нескольких исполнителей используйте клавишу Ctrl', to='reference_books.coworker', verbose_name='Исполнители')),
                ('Create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc_lo_creator', to=settings.AUTH_USER_MODEL)),
                ('Update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc_lo_modifying', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись событий ',
                'verbose_name_plural': 'Журнал оператора линий Бюлер',
            },
        ),
        migrations.CreateModel(
            name='product_packing_equipment_adjuster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(verbose_name='Дата и время контроля')),
                ('Gang', models.CharField(choices=[('line_gang1', 'Смена 1'), ('line_gang2', 'Смена 2')], max_length=30, verbose_name='Смена')),
                ('Event', models.TextField(verbose_name='Описание события')),
                ('Action', models.TextField(verbose_name='Описание события')),
                ('DateTime_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('DateTime_update', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('Coworker', models.ManyToManyField(help_text='Для указания нескольких исполнителей используйте клавишу Ctrl', to='reference_books.coworker', verbose_name='Исполнители')),
                ('Create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_pea_creator', to=settings.AUTH_USER_MODEL)),
                ('Update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_pea_modifying', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись событий ',
                'verbose_name_plural': 'Журнал наладчика фасовочного оборудования',
            },
        ),
    ]
