# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 19:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reference_books', '0008_auto_20181205_2353'),
        ('production_complex', '0002_auto_20181119_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_work_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('repairs', 'Ремонт'), ('maintenance', 'ТО'), ('works', 'Работает'), ('lieby', 'Бездействует')], max_length=100, null=True, verbose_name='Состояние станков')),
                ('plan_date', models.DateField(blank=True, null=True, verbose_name='Дата плана')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, help_text='в тоннах', max_digits=8, null=True, verbose_name='Объём плана')),
                ('DateTime_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('DateTime_update', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('Create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wp_creator', to=settings.AUTH_USER_MODEL)),
                ('Update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_wp_modifying', to=settings.AUTH_USER_MODEL)),
                ('equipement', models.ManyToManyField(blank=True, null=True, to='reference_books.machine_production', verbose_name='Оборудование')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference_books.products', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'Событие ',
                'verbose_name_plural': 'Производственный план',
            },
        ),
        migrations.AlterField(
            model_name='product_line_operator',
            name='Action',
            field=models.TextField(verbose_name='Описание работ'),
        ),
    ]
