# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-11 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_complex', '0003_auto_20181206_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_work_plan',
            name='plan_date',
        ),
        migrations.AddField(
            model_name='product_work_plan',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='product_work_plan',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
