# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_complex', '0005_auto_20181212_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_work_plan',
            name='type_task',
            field=models.CharField(choices=[('tasks', 'Задание'), ('restriction', 'Ограничение')], default='restriction', max_length=100, verbose_name='Тип записи'),
            preserve_default=False,
        ),
    ]
