# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-22 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_complex', '0006_product_work_plan_type_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_equipment_breakdown_repair',
            options={'permissions': (('list_view', 'УПРО. Просмотр списка'), ('item_view', 'УПРО. Просмотр записи'), ('item_add', 'УПРО. Добавление записи'), ('item_edit', 'УПРО. Редактирование записи')), 'verbose_name': 'Запись событий ', 'verbose_name_plural': 'Учет поломок и ремонта оборудования (УПРО)'},
        ),
        migrations.AlterModelOptions(
            name='product_line_operator',
            options={'permissions': (('list_view', 'ЖОЛБ. Просмотр списка'), ('item_view', 'ЖОЛБ. Просмотр записи'), ('item_add', 'ЖОЛБ. Добавление записи'), ('item_edit', 'ЖОЛБ. Редактирование записи')), 'verbose_name': 'Запись событий ', 'verbose_name_plural': 'Журнал оператора линий Бюлер (ЖОЛБ)'},
        ),
        migrations.AlterModelOptions(
            name='product_packing_equipment_adjuster',
            options={'permissions': (('list_view', 'ЖНФО. Просмотр списка'), ('item_view', 'ЖНФО. Просмотр записи'), ('item_add', 'ЖНФО. Добавление записи'), ('item_edit', 'ЖНФО. Редактирование записи')), 'verbose_name': 'Запись событий ', 'verbose_name_plural': 'Журнал наладчика фасовочного оборудования (ЖНФО)'},
        ),
        migrations.AlterModelOptions(
            name='product_work_plan',
            options={'permissions': (('list_view', 'ПрП. Просмотр списка'), ('item_view', 'ПрП. Просмотр записи'), ('item_add', 'ПрП. Добавление записи'), ('item_edit', 'ПрП. Редактирование записи')), 'verbose_name': 'Событие ', 'verbose_name_plural': 'Производственный план'},
        ),
    ]
