# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-22 06:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_complex', '0007_auto_20190122_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_equipment_breakdown_repair',
            options={'permissions': (('p_ebr_list_view', 'УПРО. Просмотр списка'), ('p_ebr_item_view', 'УПРО. Просмотр записи'), ('p_ebr_item_add', 'УПРО. Добавление записи'), ('p_ebr_item_edit', 'УПРО. Редактирование записи')), 'verbose_name': 'Запись событий ', 'verbose_name_plural': 'Учет поломок и ремонта оборудования (УПРО)'},
        ),
        migrations.AlterModelOptions(
            name='product_line_operator',
            options={'permissions': (('p_lo_list_view', 'ЖОЛБ. Просмотр списка'), ('p_lo_item_view', 'ЖОЛБ. Просмотр записи'), ('p_lo_item_add', 'ЖОЛБ. Добавление записи'), ('p_lo_item_edit', 'ЖОЛБ. Редактирование записи')), 'verbose_name': 'Запись событий ', 'verbose_name_plural': 'Журнал оператора линий Бюлер (ЖОЛБ)'},
        ),
        migrations.AlterModelOptions(
            name='product_packing_equipment_adjuster',
            options={'permissions': (('p_pea_list_view', 'ЖНФО. Просмотр списка'), ('p_pea_item_view', 'ЖНФО. Просмотр записи'), ('p_pea_item_add', 'ЖНФО. Добавление записи'), ('p_pea_item_edit', 'ЖНФО. Редактирование записи')), 'verbose_name': 'Запись событий ', 'verbose_name_plural': 'Журнал наладчика фасовочного оборудования (ЖНФО)'},
        ),
        migrations.AlterModelOptions(
            name='product_work_plan',
            options={'permissions': (('p_wp_list_view', 'ПрП. Просмотр списка'), ('p_wp_item_view', 'ПрП. Просмотр записи'), ('p_wp_item_add', 'ПрП. Добавление записи'), ('p_wp_item_edit', 'ПрП. Редактирование записи')), 'verbose_name': 'Событие ', 'verbose_name_plural': 'Производственный план'},
        ),
    ]
