# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_complex', '0008_auto_20190122_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_work_plan',
            old_name='end',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='product_work_plan',
            old_name='start',
            new_name='date_start',
        ),
        migrations.AlterField(
            model_name='product_work_plan',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference_books.status_machine', verbose_name='Состояние станка'),
        ),
    ]
