# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-19 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_complex', '0009_auto_20190418_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_work_plan',
            name='status_descript',
            field=models.TextField(blank=True, null=True, verbose_name='Описание работ'),
        ),
    ]
