# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 16:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference_books', '0006_auto_20181105_1247'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='elevator_shipment_wheat_to_mill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время контроля')),
                ('Moisture', models.IntegerField(help_text='Указывается в %', verbose_name='Влажность')),
                ('Nature', models.IntegerField(help_text='Указывается в грамм/литр', verbose_name='Натура')),
                ('Sil_1', models.IntegerField(verbose_name='Силос 1')),
                ('Sil_2', models.IntegerField(verbose_name='Силос 2')),
                ('Sil_3', models.IntegerField(verbose_name='Силос 3')),
                ('Gluten', models.IntegerField(help_text='Указывается в %', verbose_name='Клейковина')),
                ('Vitreous', models.IntegerField(help_text='Указывается в %', verbose_name='Стекловидность')),
                ('Yellowish', models.IntegerField(help_text='Указывается в %', verbose_name='Стекловидность')),
                ('DateTime_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('DateTime_update', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('Create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_eswm_creator', to=settings.AUTH_USER_MODEL)),
                ('Update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_eswm_modifying', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Партия ',
                'verbose_name_plural': 'Отгрузка пшеницы на мельницу',
            },
        ),
        migrations.CreateModel(
            name='mill_bagging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время контроля')),
                ('Gang', models.CharField(choices=[('line_gang1', 'Смена 1'), ('line_gang2', 'Смена 2')], max_length=30, verbose_name='Смена')),
                ('ReceivedBags_flour', models.IntegerField(verbose_name='Получено муки, мешков')),
                ('ReceivedBags_zo', models.IntegerField(verbose_name='Получено з/о, мешков')),
                ('ReceivedBags_zelen', models.IntegerField(verbose_name='Получено зелен., мешков')),
                ('HandedOverBags_flour', models.IntegerField(verbose_name='Сдано муки, мешков')),
                ('HandedOverBags_zo', models.IntegerField(verbose_name='Сдано з/о, мешков')),
                ('HandedOverBags_zelen', models.IntegerField(verbose_name='Сдано зелен., мешков')),
                ('DateTime_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('DateTime_update', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('Create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_bag_creator', to=settings.AUTH_USER_MODEL)),
                ('Update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_bag_modifying', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Смена ',
                'verbose_name_plural': 'Учёт мешков',
            },
        ),
        migrations.CreateModel(
            name='mill_control_magnetic_installations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время контроля')),
                ('DateTime_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('DateTime_update', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('CheckFailed', models.ManyToManyField(help_text='Для указания нескольких исполнителей используйте клавишу Ctrl', related_name='mi_checkfailed', to='reference_books.magnetic_installations', verbose_name='Проверку не прошли')),
                ('CheckPassed', models.ManyToManyField(help_text='Для указания нескольких исполнителей используйте клавишу Ctrl', related_name='mi_checkpassed', to='reference_books.magnetic_installations', verbose_name='Проверку прошли')),
                ('Create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_cmi_creator', to=settings.AUTH_USER_MODEL)),
                ('Update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_cmi_modifying', to=settings.AUTH_USER_MODEL)),
                ('Verifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.coworker', verbose_name='Проверяющий')),
            ],
            options={
                'verbose_name': 'Смена ',
                'verbose_name_plural': 'Контроль магнитных установок',
            },
        ),
        migrations.CreateModel(
            name='mill_grain_waste_accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время контроля')),
                ('Gang', models.CharField(choices=[('line_gang1', 'Смена 1'), ('line_gang2', 'Смена 2')], max_length=30, verbose_name='Смена')),
                ('KnockedOut', models.IntegerField(verbose_name='Выбито зерна/отходов, кг.')),
                ('Dust', models.IntegerField(verbose_name='Пыль, кг.')),
                ('DateTime_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('DateTime_update', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('Assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coworker_assistant', to='reference_books.coworker', verbose_name='Подсобный рабочий')),
                ('Create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_gwa_creator', to=settings.AUTH_USER_MODEL)),
                ('Supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coworker_supervisor', to='reference_books.coworker', verbose_name='Начальник смены')),
                ('Update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_gwa_modifying', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Смена ',
                'verbose_name_plural': 'Учёт зерна/отходов',
            },
        ),
        migrations.CreateModel(
            name='mill_laboratory_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время контроля')),
                ('Postponing_One', models.IntegerField(verbose_name='Отлёжка 1')),
                ('Postponing_Two', models.IntegerField(verbose_name='Отлёжка 2')),
                ('Postponing_Three', models.IntegerField(verbose_name='Отлёжка 3')),
                ('Grade_Top', models.IntegerField(verbose_name='Высший сорт, %')),
                ('Grade_Second', models.IntegerField(verbose_name='Второй сорт, %')),
                ('SieveResidue125', models.IntegerField(verbose_name='Остаток на сите 12,5')),
                ('SieveResidue245', models.IntegerField(verbose_name='Остаток на сите 24,5')),
                ('Inclusion_Black', models.CharField(max_length=50, verbose_name='Вкрапления черные')),
                ('Inclusion_Brown', models.CharField(max_length=50, verbose_name='Вкрапления коричневые')),
                ('BAKBHM', models.CharField(max_length=50, verbose_name='БАК БХМ')),
                ('DateTime_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('DateTime_update', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('Create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_lw_creator', to=settings.AUTH_USER_MODEL)),
                ('Update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_lw_modifying', to=settings.AUTH_USER_MODEL)),
                ('Verifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.coworker', verbose_name='Проверяющий')),
            ],
            options={
                'verbose_name': 'Смена ',
                'verbose_name_plural': 'Журнал лабораторных работ',
            },
        ),
    ]
