# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill_complex', '0002_auto_20181117_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator_shipment_wheat_to_mill',
            name='DateTime',
            field=models.DateTimeField(default='2018-01-01 12:12', verbose_name='Дата и время контроля'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mill_bagging',
            name='DateTime',
            field=models.DateTimeField(default='2018-01-01 12:12', verbose_name='Дата и время контроля'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mill_control_magnetic_installations',
            name='DateTime',
            field=models.DateTimeField(default='2018-01-01 12:12', verbose_name='Дата и время контроля'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mill_grain_waste_accounting',
            name='DateTime',
            field=models.DateTimeField(default='2018-01-01 12:12', verbose_name='Дата и время контроля'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mill_laboratory_work',
            name='DateTime',
            field=models.DateTimeField(default='2018-01-01 20:00', verbose_name='Дата и время контроля'),
            preserve_default=False,
        ),
    ]
