# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mill_complex', '0003_auto_20181117_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elevator_shipment_wheat_to_mill',
            old_name='DateTime',
            new_name='DateTime_word',
        ),
        migrations.RenameField(
            model_name='mill_bagging',
            old_name='DateTime',
            new_name='DateTime_word',
        ),
        migrations.RenameField(
            model_name='mill_control_magnetic_installations',
            old_name='DateTime',
            new_name='DateTime_word',
        ),
        migrations.RenameField(
            model_name='mill_grain_waste_accounting',
            old_name='DateTime',
            new_name='DateTime_word',
        ),
        migrations.RenameField(
            model_name='mill_laboratory_work',
            old_name='DateTime',
            new_name='DateTime_word',
        ),
    ]
