# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-22 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mill_complex', '0005_auto_20181117_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elevator_shipment_wheat_to_mill',
            options={'permissions': (('list_view', 'ОПМ. Просмотр списка'), ('item_view', 'ОПМ. Просмотр записи'), ('item_add', 'ОПМ. Добавление записи'), ('item_edit', 'ОПМ. Редактирование записи')), 'verbose_name': 'Партия ', 'verbose_name_plural': 'Отгрузка пшеницы на мельницу (ОПМ)'},
        ),
        migrations.AlterModelOptions(
            name='mill_bagging',
            options={'permissions': (('list_view', 'Учет мешков. Просмотр списка'), ('item_view', 'Учет мешков. Просмотр записи'), ('item_add', 'Учет мешков. Добавление записи'), ('item_edit', 'Учет мешков. Редактирование записи')), 'verbose_name': 'Смена ', 'verbose_name_plural': 'Учёт мешков'},
        ),
        migrations.AlterModelOptions(
            name='mill_control_magnetic_installations',
            options={'permissions': (('list_view', 'КМУ. Просмотр списка'), ('item_view', 'КМУ. Просмотр записи'), ('item_add', 'КМУ. Добавление записи'), ('item_edit', 'КМУ. Редактирование записи')), 'verbose_name': 'Смена ', 'verbose_name_plural': 'Контроль магнитных установок (КМУ)'},
        ),
        migrations.AlterModelOptions(
            name='mill_grain_waste_accounting',
            options={'permissions': (('list_view', 'УЗО. Просмотр списка'), ('item_view', 'УЗО. Просмотр записи'), ('item_add', 'УЗО. Добавление записи'), ('item_edit', 'УЗО. Редактирование записи')), 'verbose_name': 'Смена ', 'verbose_name_plural': 'Учёт зерна/отходов (УЗО)'},
        ),
        migrations.AlterModelOptions(
            name='mill_laboratory_work',
            options={'permissions': (('list_view', 'ЖЛр. Просмотр списка'), ('item_view', 'ЖЛр. Просмотр записи'), ('item_add', 'ЖЛр. Добавление записи'), ('item_edit', 'ЖЛр. Редактирование записи')), 'verbose_name': 'Смена ', 'verbose_name_plural': 'Журнал лабораторных работ (ЖЛр)'},
        ),
    ]
