# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-30 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill_complex', '0008_auto_20190129_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mill_laboratory_work',
            name='Passage_GradeSecond',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Проход 2ой сорт'),
        ),
    ]
