# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0012_bhm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mill_complex', '0010_auto_20190131_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='mill_technological',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_word', models.DateField(verbose_name='Дата контроля')),
                ('Time_word', models.TimeField(verbose_name='Время контроля')),
                ('Gang', models.CharField(choices=[('day_shift', 'Смена дневная'), ('night_shift', 'Смена ночная')], max_length=30, verbose_name='Смена')),
                ('Prod_Semolina', models.IntegerField(verbose_name='Манка')),
                ('Prod_TopGrade_enum', models.IntegerField(verbose_name='Высший сорт счетчик (весы)')),
                ('Prod_SecondGrade_enum', models.IntegerField(verbose_name='2 сорт счетчик (весы)')),
                ('Prod_Bran_enum', models.IntegerField(verbose_name='Отруби счетчик (весы)')),
                ('Prod_GrainWaste', models.IntegerField(verbose_name='Зерноотходы')),
                ('Prod_Bran2Varieties', models.IntegerField(verbose_name='Отруби 2сорта')),
                ('KnockedOut_TopGrade_start', models.IntegerField(verbose_name='Высший сорт № поддона от, кг')),
                ('KnockedOut_TopGrade_stop', models.IntegerField(verbose_name='Высший сорт № поддона до, кг')),
                ('KnockedOut_SecondGrade', models.IntegerField(verbose_name='2 сорт, кол-во поддонов')),
                ('KnockedOut_Semolina', models.IntegerField(verbose_name='Манка, кг.')),
                ('Trans_Workshop', models.IntegerField(verbose_name='Перекачено в цех счетчик, кг')),
                ('Description_work', models.TextField(verbose_name='Произведенные работы во время смены')),
                ('DateTime_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('DateTime_update', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('BHM', models.ManyToManyField(to='reference_books.BHM', verbose_name='Показание муки в БХМ, в %')),
                ('Create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_tech_creator', to=settings.AUTH_USER_MODEL)),
                ('Update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_tech_modifying', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Смена ',
                'permissions': (('m_tech_list_view', 'ТЖ. Просмотр списка'), ('m_tech_item_view', 'ТЖ. Просмотр записи'), ('m_tech_item_add', 'ТЖ. Добавление записи'), ('m_tech_item_edit', 'ТЖ. Редактирование записи')),
                'verbose_name_plural': 'Технологический журнал (ТЖ)',
            },
        ),
    ]
