# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-01 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill_complex', '0011_mill_technological'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mill_technological',
            name='BHM',
            field=models.ManyToManyField(blank=True, null=True, to='reference_books.BHM', verbose_name='Показание муки в БХМ, в %'),
        ),
    ]
