# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-02 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mill_complex', '0012_auto_20190201_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='mill_technological_child_bhm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BHM', models.CharField(max_length=15, verbose_name='Показание муки в БХМ, в %')),
            ],
        ),
        migrations.RemoveField(
            model_name='mill_technological',
            name='BHM',
        ),
        migrations.AddField(
            model_name='mill_technological_child_bhm',
            name='parent_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mill_complex.mill_technological'),
        ),
    ]
