# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-03 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mill_complex', '0013_auto_20190202_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mill_technological_child_bhm',
            name='parent_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mill_complex.mill_technological'),
        ),
    ]
