# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-14 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0014_sil'),
        ('mill_complex', '0015_auto_20190203_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='elevator_shipment_wheat_to_mill_child_sil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grain', models.IntegerField(verbose_name='кг')),
            ],
        ),
        migrations.RemoveField(
            model_name='elevator_shipment_wheat_to_mill',
            name='Sil_1',
        ),
        migrations.RemoveField(
            model_name='elevator_shipment_wheat_to_mill',
            name='Sil_2',
        ),
        migrations.RemoveField(
            model_name='elevator_shipment_wheat_to_mill',
            name='Sil_3',
        ),
        migrations.AddField(
            model_name='elevator_shipment_wheat_to_mill_child_sil',
            name='parent_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mill_complex.elevator_shipment_wheat_to_mill'),
        ),
        migrations.AddField(
            model_name='elevator_shipment_wheat_to_mill_child_sil',
            name='sil_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference_books.Sil', verbose_name='Силос №'),
        ),
    ]
