# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill_complex', '0016_auto_20190214_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='mill_technological',
            name='KnockedOut_TopGrade',
            field=models.IntegerField(default=0, verbose_name='Высший сорт, поддонов'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mill_technological',
            name='KnockedOut_SecondGrade',
            field=models.IntegerField(verbose_name='2 сорт, поддонов'),
        ),
        migrations.AlterField(
            model_name='mill_technological',
            name='KnockedOut_TopGrade_start',
            field=models.IntegerField(verbose_name='Высший сорт № поддона от'),
        ),
        migrations.AlterField(
            model_name='mill_technological',
            name='KnockedOut_TopGrade_stop',
            field=models.IntegerField(verbose_name='Высший сорт № поддона до'),
        ),
    ]
