# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill_complex', '0018_auto_20190226_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator_grain_intake',
            name='CarModel',
            field=models.CharField(default='', max_length=100, verbose_name='Модель автомобиля'),
            preserve_default=False,
        ),
    ]
