# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mill_complex', '0019_elevator_grain_intake_carmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator_grain_intake',
            name='CerealCrop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference_books.cereal_crop', verbose_name='Зерновая культура'),
        ),
    ]
