# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-03 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill_complex', '0020_auto_20190228_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator_grain_intake',
            name='WeightGross',
            field=models.IntegerField(verbose_name='Вес брутто, кг'),
        ),
    ]
