# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-10 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill_complex', '0021_auto_20190303_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mill_control_magnetic_installations',
            name='Verifier',
        ),
        migrations.RemoveField(
            model_name='mill_laboratory_work',
            name='Verifier',
        ),
        migrations.AddField(
            model_name='elevator_grain_waste_accounting',
            name='GrainWasteTopGrade',
            field=models.IntegerField(default=0, verbose_name='Зерноотходы 1 сорта, кг.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elevator_shipment_wheat_to_mill_child_sil',
            name='party',
            field=models.IntegerField(default=0, verbose_name='%'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mill_control_magnetic_installations',
            name='Gang',
            field=models.CharField(choices=[('day_shift', 'Смена дневная'), ('night_shift', 'Смена ночная')], default='', max_length=30, verbose_name='Смена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mill_laboratory_work',
            name='Gang',
            field=models.CharField(choices=[('day_shift', 'Смена дневная'), ('night_shift', 'Смена ночная')], default='', max_length=30, verbose_name='Смена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mill_laboratory_work',
            name='GrainBlack',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Черных'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mill_laboratory_work',
            name='GrainBraun',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Коричневых'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mill_laboratory_work',
            name='GrainGreen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Зелёных'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mill_laboratory_work',
            name='GrainWhite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Белых'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elevator_grain_waste_accounting',
            name='GrainWasteSecondGrade',
            field=models.IntegerField(verbose_name='Зерноотходы 2 сорта, кг.'),
        ),
        migrations.AlterField(
            model_name='elevator_shipment_wheat_to_mill',
            name='Gluten',
            field=models.DecimalField(decimal_places=2, help_text='Указывается в %', max_digits=4, verbose_name='Клейковина'),
        ),
        migrations.AlterField(
            model_name='elevator_shipment_wheat_to_mill',
            name='Moisture',
            field=models.DecimalField(decimal_places=2, help_text='Указывается в %', max_digits=4, verbose_name='Влажность'),
        ),
        migrations.AlterField(
            model_name='elevator_shipment_wheat_to_mill',
            name='Vitreous',
            field=models.DecimalField(decimal_places=2, help_text='Указывается в %', max_digits=4, verbose_name='Стекловидность'),
        ),
        migrations.AlterField(
            model_name='elevator_shipment_wheat_to_mill',
            name='Yellowish',
            field=models.DecimalField(decimal_places=2, help_text='Указывается в %', max_digits=4, verbose_name='Желтизна'),
        ),
        migrations.AlterField(
            model_name='mill_laboratory_work',
            name='MetalImpurity_TopGrade',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Металлопримесь в/c'),
        ),
    ]
