# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill_complex', '0023_auto_20190310_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mill_technological',
            name='KnockedOut_TopGrade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высший сорт, поддонов'),
        ),
    ]
