# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-15 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill_complex', '0024_auto_20190312_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator_shipment_wheat_to_mill',
            name='Nature',
            field=models.DecimalField(decimal_places=2, help_text='Указывается в грамм/литр', max_digits=6, verbose_name='Натура'),
        ),
        migrations.AlterField(
            model_name='elevator_shipment_wheat_to_mill_child_sil',
            name='grain',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='кг'),
        ),
        migrations.AlterField(
            model_name='elevator_shipment_wheat_to_mill_child_sil',
            name='party',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='%'),
        ),
    ]
