# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-27 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0027_auto_20190626_1703'),
        ('mill_complex', '0025_auto_20190315_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator_grain_intake',
            name='Factory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reference_books.Factory', verbose_name='Организация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elevator_grain_waste_accounting',
            name='Factory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reference_books.Factory', verbose_name='Организация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elevator_shipment_wheat_to_mill',
            name='Factory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reference_books.Factory', verbose_name='Организация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mill_bagging',
            name='Factory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reference_books.Factory', verbose_name='Организация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mill_control_magnetic_installations',
            name='Factory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reference_books.Factory', verbose_name='Организация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mill_grain_waste_accounting',
            name='Factory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reference_books.Factory', verbose_name='Организация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mill_laboratory_work',
            name='Factory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reference_books.Factory', verbose_name='Организация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mill_storage_flour_accounting',
            name='Factory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reference_books.Factory', verbose_name='Организация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mill_technological',
            name='Factory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reference_books.Factory', verbose_name='Организация'),
            preserve_default=False,
        ),
    ]
